# font settings
typography:
  # external font source
  url: https://fonts.googleapis.com/css?family=Indie+Flower|Pacifico|Amatic+SC

  # header styling
  header:
    font: Indie Flower
    size: 140
    color: "#000"

  weekend:
    color: "#97e5a2"

  # day number styling
  dayNumber:
    font: Pacifico
    size: 20
    color: "#888"

  # day name styling
  dayName:
    font: Amatic SC
    size: 15
    color: "#AAA"

  # month name styling
  monthName:
    font: Indie Flower
    size: 60
    color: "#000"

# line stylings
lines:
  # month divider styling
  monthDivider:
    color: "#2db640"
    width: 5

  # day stylings
  dayDivider:
    color: "#2db640"
    width: 1

# month names starting from January
months:
  - Januar
  - Februar
  - März
  - April
  - Mai
  - Juni
  - Juli
  - August
  - September
  - Oktober
  - November
  - Dezember

# day names starting from Sunday
days:
  - So
  - Mo
  - Di
  - Mi
  - Do
  - Fr
  - Sa
